/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.HashSet;
import java.util.Set;

public class Library {
//    public boolean someLibraryMethod() {
//        return true;
//    }
    public int[] roll(int n){
        int[] arr = new int[n];
        int random;
        for(int i=0; i<n; i++){
            random = (int)(Math.random() * 6 +1 );
            arr[i] = random;
        }
        return arr;
    }

    public boolean containsDuplicates(int [] arr){
        Set<Integer> set = new HashSet<>();
        for(int i: arr) {
            set.add(i);
        }
        return arr.length > set.size();
    }

    public double calculatingAverages(int[] arr){
        double avg=0, sum = 0;
        for(int i=0; i<arr.length; i++){
            sum+= arr[i];
        }
        if(arr.length > 0)
            avg = sum / arr.length;

        return avg;
    }



    public int[] calculateArraysAverage(int[][] arr){
        double avg = 0;
        double min;
        int index = -1;
        if(arr.length > 0){
            min = calculatingAverages(arr[0]);
            index = 0;
            for(int i=1; i<arr.length; i++){
                avg = calculatingAverages(arr[i]);
                if(avg < min){
                    min = avg;
                    index = i;
                }
            }
            return arr[index];
        }else{
            return new int[0];
        }

    }
}
