/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args){
        Restaurant burgerizz = new Restaurant("Burgerizz", 3, "$$");
        System.out.println(burgerizz.addReview("The mexican burger was very delicious", "AbdalQader Mhemed", 5));
        System.out.println(burgerizz.toString());

    }
}
