/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import com.google.common.annotations.VisibleForTesting;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class App {

    public static void main(String[] args) {
        String dir = System.getProperty("user.dir");
        if(dir.charAt(dir.length()-1) == 'p'){
            System.out.println("Running using Gradle/Test");
            int one = javaScriptLinter("../one.js");
            int empty = javaScriptLinter("../empty.js");
            int few = javaScriptLinter("../few.js");
            int correct = javaScriptLinter("../correct.js");
            int many = javaScriptLinter("../gates.js");
        }else{
            System.out.println("Running using IntelliJ");
            int one = javaScriptLinter("./one.js");
            int empty = javaScriptLinter("./empty.js");
            int few = javaScriptLinter("./few.js");
            int correct = javaScriptLinter("./correct.js");
            int many = javaScriptLinter("./gates.js");
        }

    }
    public static int javaScriptLinter(String fileName){
        FileReader file = null;
        BufferedReader reader = null;
        String line;
        char c;
        int lineNumber = 0;
        int missedSemiColons = 0;
        try {
            file = new FileReader(fileName);
            reader = new BufferedReader(file);
            while ((line = reader.readLine()) != null){
                lineNumber++;
                if(line.length() > 0){
                    c = line.charAt(line.length() -1);
                    if(check(line, c)){
                        missedSemiColons++;
                        System.out.println("Line "+ lineNumber +": Missing semicolon.");
                    }
                }
            }
            reader.close();
        }catch (IOException e){
            System.out.println(e.getMessage());
        }
        return missedSemiColons;
    }
    public static boolean check(String line, char c){
            if(line.contains("if") || line.contains("else"))
                return false;
            else if(c == ')')
                return true;
            else if(c!='{' && c!= '}' && c!='\n' && c!=';')
                return true;
            else
            return false;
    }
}
