/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testNumberOfStartsbeforeChange() {
        Restaurant burgerizz = new Restaurant("Burgerizz", 3, "$$");
        int numberOfStarts = burgerizz.getStars();
        assertEquals("should test starts before review", 3, numberOfStarts);


    }
    @Test public void testNumberOfStartsAfterChange() {
        Restaurant burgerizz = new Restaurant("Burgerizz", 3, "$$");
        burgerizz.addReview("The mexican burger was very delicious", "AbdalQader Mhemed", 5);
        int numberOfStarts = burgerizz.getStars();
        assertEquals("should test starts before review", 5, numberOfStarts);

    }
}
