/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.checkerframework.checker.units.qual.A;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {


    @Test
    public void testLinterOneError(){
        int one = App.javaScriptLinter("../one.js");
        assertEquals("This method tests 1 error in file ", 1,one);
    }
    @Test
    public void testLinterFewErrors() {
        int few = App.javaScriptLinter("../few.js");
        assertEquals("This method tests 2 errors in file ", 2, few);
    }
    @Test
    public void testLinterEmptyFile(){
        int empty = App.javaScriptLinter("../empty.js");

        assertEquals("This method tests 0 errors in file ", 0,empty);

    }
    @Test
    public void testLinterManyErrors(){
        int many = App.javaScriptLinter("../gates.js");
        assertEquals("This method tests one error in file ", 42,many);
    }
    @Test
    public void testLinterNoErrors(){
        int correct = App.javaScriptLinter("../correct.js");
        assertEquals("This method tests 0 error in file ", 0,correct);
    }
}
