/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.checkerframework.checker.units.qual.A;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {


    @Test
    public void testJavaScriptLinter(){
        System.out.println("Working Directory = " + System.getProperty("user.dir"));
        int one = App.javaScriptLinter("../one.js");
        int empty = App.javaScriptLinter("../empty.js");
        int few = App.javaScriptLinter("../few.js");
        int correct = App.javaScriptLinter("../correct.js");
        int many = App.javaScriptLinter("../gates.js");
        assertEquals("This method tests 1 error in file ", 1,one);
        assertEquals("This method tests 0 errors in file ", 0,empty);
        assertEquals("This method tests 2 errors in file ", 2,few);
        assertEquals("This method tests 0 error in file ", 0,correct);
        assertEquals("This method tests one error in file ", 46,many);
    }
}
